"""Add PM-recommended fields and markdown_content to help_core.analysis_results

Adds columns for the 4 PM-recommended classification fields (area_operacional,
complexity_level, mentions_systems, escalation_present) and the markdown_content
column generated by the markdown_generator post-processor.

Revision ID: 021
Revises: 020
Create Date: 2026-10-07
"""
from alembic import op

revision = "021"
down_revision = "020"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        ALTER TABLE help_core.analysis_results
        ADD COLUMN IF NOT EXISTS area_operacional TEXT,
        ADD COLUMN IF NOT EXISTS complexity_level TEXT
            CHECK (complexity_level IN ('basico', 'intermediario', 'avancado')),
        ADD COLUMN IF NOT EXISTS mentions_systems TEXT[] DEFAULT '{}'::TEXT[],
        ADD COLUMN IF NOT EXISTS escalation_present BOOLEAN NOT NULL DEFAULT false,
        ADD COLUMN IF NOT EXISTS markdown_content TEXT;
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_hc_analysis_area_op
        ON help_core.analysis_results (area_operacional);
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_hc_analysis_complexity
        ON help_core.analysis_results (complexity_level);
    """)


def downgrade():
    op.execute("""
        ALTER TABLE help_core.analysis_results
        DROP COLUMN IF EXISTS area_operacional,
        DROP COLUMN IF EXISTS complexity_level,
        DROP COLUMN IF EXISTS mentions_systems,
        DROP COLUMN IF EXISTS escalation_present,
        DROP COLUMN IF EXISTS markdown_content;
    """)
