import type {
  Politician,
  Article,
  NewsSource,
  Entity,
  Relationship,
  LegalMilestone,
  GraphData,
  Stats,
} from "@/types";

// ─── News Sources ───────────────────────────────────────────────────────────

export const NEWS_SOURCES: NewsSource[] = [
  {
    id: "folha",
    name: "Folha de S.Paulo",
    url: "https://folha.uol.com.br",
    reliability: 0.92,
  },
  {
    id: "g1",
    name: "G1",
    url: "https://g1.globo.com",
    reliability: 0.88,
  },
  {
    id: "estadao",
    name: "O Estado de S. Paulo",
    url: "https://estadao.com.br",
    reliability: 0.91,
  },
  {
    id: "uol",
    name: "UOL Notícias",
    url: "https://uol.com.br",
    reliability: 0.82,
  },
  {
    id: "congresso-em-foco",
    name: "Congresso em Foco",
    url: "https://congressoemfoco.uol.com.br",
    reliability: 0.85,
  },
  {
    id: "agencia-brasil",
    name: "Agência Brasil",
    url: "https://agenciabrasil.ebc.com.br",
    reliability: 0.87,
  },
  {
    id: "poder360",
    name: "Poder360",
    url: "https://poder360.com.br",
    reliability: 0.89,
  },
  {
    id: "the-intercept",
    name: "The Intercept Brasil",
    url: "https://theintercept.com/brasil",
    reliability: 0.83,
  },
];

// ─── Entities ────────────────────────────────────────────────────────────────

export const ENTITIES: Entity[] = [
  {
    id: "ent-odebrecht",
    slug: "odebrecht",
    name: "Odebrecht S.A.",
    type: "company",
    description: "Conglomerado brasileiro de construção civil envolvido na Lava Jato",
    cnpj: "09.014.109/0001-45",
  },
  {
    id: "ent-petrobras",
    slug: "petrobras",
    name: "Petrobras",
    type: "government",
    description: "Empresa estatal de petróleo e gás",
    cnpj: "33.000.167/0001-01",
  },
  {
    id: "ent-bndes",
    slug: "bndes",
    name: "BNDES",
    type: "government",
    description: "Banco Nacional de Desenvolvimento Econômico e Social",
    cnpj: "33.657.248/0001-89",
  },
  {
    id: "ent-embraer",
    slug: "embraer",
    name: "Embraer S.A.",
    type: "company",
    description: "Fabricante brasileira de aeronaves",
    cnpj: "07.689.002/0001-89",
  },
  {
    id: "ent-friboi",
    slug: "jbs",
    name: "JBS S.A.",
    type: "company",
    description: "Maior empresa de proteínas animal do mundo",
    cnpj: "02.916.265/0001-60",
  },
  {
    id: "ent-stj",
    slug: "stj",
    name: "Superior Tribunal de Justiça",
    type: "government",
    description: "Tribunal superior do sistema judiciário brasileiro",
  },
  {
    id: "ent-mpf",
    slug: "mpf",
    name: "Ministério Público Federal",
    type: "government",
    description: "Órgão responsável pela defesa da ordem jurídica",
  },
  {
    id: "ent-tcu",
    slug: "tcu",
    name: "Tribunal de Contas da União",
    type: "government",
    description: "Órgão de controle externo federal brasileiro",
  },
  {
    id: "ent-cni",
    slug: "cni",
    name: "Confederação Nacional da Indústria",
    type: "organization",
    description: "Representa os interesses do setor industrial brasileiro",
  },
  {
    id: "ent-cut",
    slug: "cut",
    name: "Central Única dos Trabalhadores",
    type: "organization",
    description: "Central sindical brasileira",
  },
];

// ─── Politicians ─────────────────────────────────────────────────────────────

export const POLITICIANS: Politician[] = [
  {
    id: "pol-lula",
    slug: "luiz-inacio-lula-da-silva",
    name: "Luiz Inácio Lula da Silva",
    party: "PT",
    partyColor: "#CC0000",
    uf: "SP",
    role: "Presidente da República",
    bio: "35º e 39º Presidente do Brasil. Ex-metalúrgico e líder sindical, fundador do Partido dos Trabalhadores.",
    score: 42,
    articleCount: 312,
    maxSeverity: "high",
    milestoneCount: 8,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-bolsonaro",
    slug: "jair-messias-bolsonaro",
    name: "Jair Messias Bolsonaro",
    party: "PL",
    partyColor: "#002776",
    uf: "RJ",
    role: "Ex-Presidente da República",
    bio: "38º Presidente do Brasil (2019-2022). Ex-militar e deputado federal por 27 anos.",
    score: 18,
    articleCount: 487,
    maxSeverity: "critical",
    milestoneCount: 15,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-alckmin",
    slug: "geraldo-alckmin",
    name: "Geraldo Alckmin",
    party: "PSB",
    partyColor: "#FF6600",
    uf: "SP",
    role: "Vice-Presidente da República",
    bio: "Vice-Presidente do Brasil. Ex-governador de São Paulo por quatro mandatos.",
    score: 71,
    articleCount: 89,
    maxSeverity: "medium",
    milestoneCount: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-moro",
    slug: "sergio-moro",
    name: "Sergio Moro",
    party: "União Brasil",
    partyColor: "#FFD700",
    uf: "PR",
    role: "Senador",
    bio: "Ex-juiz federal que conduziu a Operação Lava Jato. Atual senador pelo Paraná.",
    score: 55,
    articleCount: 234,
    maxSeverity: "high",
    milestoneCount: 6,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-temer",
    slug: "michel-temer",
    name: "Michel Temer",
    party: "MDB",
    partyColor: "#00A859",
    uf: "SP",
    role: "Ex-Presidente da República",
    bio: "37º Presidente do Brasil (2016-2018). Ex-deputado federal e professor de direito constitucional.",
    score: 22,
    articleCount: 198,
    maxSeverity: "critical",
    milestoneCount: 9,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-cunha",
    slug: "eduardo-cunha",
    name: "Eduardo Cunha",
    party: "MDB",
    partyColor: "#00A859",
    uf: "RJ",
    role: "Ex-Deputado Federal",
    bio: "Ex-presidente da Câmara dos Deputados. Condenado na Lava Jato.",
    score: 5,
    articleCount: 156,
    maxSeverity: "critical",
    milestoneCount: 12,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-amoedo",
    slug: "joao-amoedo",
    name: "João Amoêdo",
    party: "Novo",
    partyColor: "#FF6600",
    uf: "RJ",
    role: "Ex-Candidato à Presidência",
    bio: "Empresário e ex-candidato à presidência. Fundador do Partido Novo.",
    score: 88,
    articleCount: 34,
    maxSeverity: "low",
    milestoneCount: 0,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-gleisi",
    slug: "gleisi-hoffmann",
    name: "Gleisi Hoffmann",
    party: "PT",
    partyColor: "#CC0000",
    uf: "PR",
    role: "Deputada Federal",
    bio: "Presidenta do PT. Ex-ministra da Casa Civil do governo Dilma.",
    score: 48,
    articleCount: 121,
    maxSeverity: "high",
    milestoneCount: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-haddad",
    slug: "fernando-haddad",
    name: "Fernando Haddad",
    party: "PT",
    partyColor: "#CC0000",
    uf: "SP",
    role: "Ministro da Fazenda",
    bio: "Ministro da Fazenda. Ex-prefeito de São Paulo e ex-candidato à presidência.",
    score: 67,
    articleCount: 145,
    maxSeverity: "medium",
    milestoneCount: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-flavio",
    slug: "flavio-bolsonaro",
    name: "Flávio Bolsonaro",
    party: "PL",
    partyColor: "#002776",
    uf: "RJ",
    role: "Senador",
    bio: "Senador pelo Rio de Janeiro. Filho do ex-presidente Jair Bolsonaro.",
    score: 25,
    articleCount: 167,
    maxSeverity: "critical",
    milestoneCount: 7,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-rodrigo-maia",
    slug: "rodrigo-maia",
    name: "Rodrigo Maia",
    party: "União Brasil",
    partyColor: "#FFD700",
    uf: "RJ",
    role: "Ex-Deputado Federal",
    bio: "Ex-presidente da Câmara dos Deputados. Exerceu o cargo de 2016 a 2021.",
    score: 58,
    articleCount: 78,
    maxSeverity: "medium",
    milestoneCount: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-marina",
    slug: "marina-silva",
    name: "Marina Silva",
    party: "Rede",
    partyColor: "#00B4D8",
    uf: "AC",
    role: "Ministra do Meio Ambiente",
    bio: "Ministra do Meio Ambiente e Mudança do Clima. Ex-senadora e ex-ministra do governo Lula I.",
    score: 84,
    articleCount: 112,
    maxSeverity: "low",
    milestoneCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-ciro",
    slug: "ciro-gomes",
    name: "Ciro Gomes",
    party: "PDT",
    partyColor: "#009B3A",
    uf: "CE",
    role: "Ex-Candidato à Presidência",
    bio: "Político cearense com longa trajetória. Ex-governador, ex-ministro e múltiplo candidato à presidência.",
    score: 62,
    articleCount: 93,
    maxSeverity: "medium",
    milestoneCount: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-fux",
    slug: "luiz-fux",
    name: "Luiz Fux",
    party: "Sem Partido",
    partyColor: "#6B7280",
    uf: "RJ",
    role: "Ex-Presidente do STF",
    bio: "Ministro do Supremo Tribunal Federal. Presidiu o STF de 2020 a 2022.",
    score: 76,
    articleCount: 45,
    maxSeverity: "low",
    milestoneCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-dilma",
    slug: "dilma-rousseff",
    name: "Dilma Rousseff",
    party: "PT",
    partyColor: "#CC0000",
    uf: "MG",
    role: "Ex-Presidenta da República",
    bio: "36ª Presidente do Brasil (2011-2016). Sofreu impeachment em 2016. Atual presidente do BRICS.",
    score: 44,
    articleCount: 278,
    maxSeverity: "high",
    milestoneCount: 7,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-lira",
    slug: "arthur-lira",
    name: "Arthur Lira",
    party: "PP",
    partyColor: "#1e3a8a",
    uf: "AL",
    role: "Ex-Presidente da Câmara",
    bio: "Ex-presidente da Câmara dos Deputados. Deputado federal por Alagoas.",
    score: 31,
    articleCount: 189,
    maxSeverity: "critical",
    milestoneCount: 5,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-guedes",
    slug: "paulo-guedes",
    name: "Paulo Guedes",
    party: "Sem Partido",
    partyColor: "#6B7280",
    uf: "RJ",
    role: "Ex-Ministro da Economia",
    bio: "Ex-ministro da Economia do governo Bolsonaro. Economista formado pela Universidade de Chicago.",
    score: 45,
    articleCount: 134,
    maxSeverity: "high",
    milestoneCount: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-weintraub",
    slug: "abraham-weintraub",
    name: "Abraham Weintraub",
    party: "Sem Partido",
    partyColor: "#6B7280",
    uf: "SP",
    role: "Ex-Ministro da Educação",
    bio: "Ex-ministro da Educação do governo Bolsonaro. Atualmente exilado nos EUA.",
    score: 12,
    articleCount: 89,
    maxSeverity: "critical",
    milestoneCount: 6,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-tabata",
    slug: "tabata-amaral",
    name: "Tabata Amaral",
    party: "PSB",
    partyColor: "#FF6600",
    uf: "SP",
    role: "Deputada Federal",
    bio: "Deputada federal por São Paulo. Fundadora do movimento Acredito. Ex-candidata à prefeitura de SP.",
    score: 91,
    articleCount: 56,
    maxSeverity: "info",
    milestoneCount: 0,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "pol-kim",
    slug: "kim-kataguiri",
    name: "Kim Kataguiri",
    party: "União Brasil",
    partyColor: "#FFD700",
    uf: "SP",
    role: "Deputado Federal",
    bio: "Deputado federal por São Paulo. Co-fundador do MBL (Movimento Brasil Livre).",
    score: 72,
    articleCount: 67,
    maxSeverity: "low",
    milestoneCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
];

// ─── Articles ─────────────────────────────────────────────────────────────────

export const ARTICLES: Article[] = [
  {
    id: "art-001",
    title: "Lava Jato: condenações e absolvições marcam 10 anos da operação",
    summary: "Dez anos após o início da Operação Lava Jato, balanço mostra que 174 pessoas foram condenadas e a operação levantou R$ 4,3 bilhões em multas e ressarcimentos.",
    url: "https://exemplo.folha.uol.com.br/poder/2024/03/lava-jato-10-anos.html",
    source: NEWS_SOURCES[0],
    publishedAt: "2024-03-17T10:00:00Z",
    severity: "critical",
    truthScore: 0.95,
    politicianIds: ["pol-lula", "pol-temer", "pol-cunha"],
    tags: ["lava-jato", "corrupcao", "penal"],
  },
  {
    id: "art-002",
    title: "Bolsonaro é indiciado pela PF por tentativa de golpe de Estado",
    summary: "A Polícia Federal indiciou o ex-presidente Jair Bolsonaro por tentativa de golpe de Estado após as eleições de 2022, juntamente com mais de 30 investigados.",
    url: "https://exemplo.g1.globo.com/politica/2024/11/bolsonaro-indiciado-pf-golpe.html",
    source: NEWS_SOURCES[1],
    publishedAt: "2024-11-22T15:30:00Z",
    severity: "critical",
    truthScore: 0.98,
    politicianIds: ["pol-bolsonaro"],
    tags: ["golpe", "inquerito", "pf"],
  },
  {
    id: "art-003",
    title: "Alckmin defende reforma tributária como prioridade econômica",
    summary: "O vice-presidente Geraldo Alckmin afirmou que a implementação da reforma tributária é fundamental para o crescimento econômico do país nos próximos anos.",
    url: "https://exemplo.estadao.com.br/politica/alckmin-reforma-tributaria-2024.html",
    source: NEWS_SOURCES[2],
    publishedAt: "2024-08-15T09:00:00Z",
    severity: "info",
    truthScore: 0.92,
    politicianIds: ["pol-alckmin"],
    tags: ["reforma-tributaria", "economia"],
  },
  {
    id: "art-004",
    title: "Moro pede ao STJ anulação de condenações da Lava Jato",
    summary: "O senador Sergio Moro recorreu ao STJ solicitando a anulação das condenações decorrentes da Lava Jato após decisão anterior do STF sobre a parcialidade da operação.",
    url: "https://exemplo.uol.com.br/politica/moro-stj-lavajato.htm",
    source: NEWS_SOURCES[3],
    publishedAt: "2024-05-10T11:00:00Z",
    severity: "high",
    truthScore: 0.88,
    politicianIds: ["pol-moro", "pol-lula"],
    tags: ["lava-jato", "stf", "habeas-corpus"],
  },
  {
    id: "art-005",
    title: "Flávio Bolsonaro: caso 'rachadinha' retoma tramitação no TJRJ",
    summary: "O Tribunal de Justiça do Rio de Janeiro retomou a análise do caso 'rachadinha' envolvendo o senador Flávio Bolsonaro e o desvio de parte dos salários de assessores.",
    url: "https://exemplo.congressoemfoco.uol.com.br/legislativo/flavio-bolsonaro-rachadinha.html",
    source: NEWS_SOURCES[4],
    publishedAt: "2024-06-20T14:00:00Z",
    severity: "critical",
    truthScore: 0.93,
    politicianIds: ["pol-flavio"],
    tags: ["rachadinha", "corrupcao", "peculato"],
  },
  {
    id: "art-006",
    title: "Haddad anuncia medidas de ajuste fiscal para 2025",
    summary: "O ministro Fernando Haddad apresentou pacote de medidas fiscais incluindo corte de gastos e revisão de benefícios para equilibrar as contas públicas em 2025.",
    url: "https://exemplo.agenciabrasil.ebc.com.br/economia/haddad-ajuste-fiscal-2025.html",
    source: NEWS_SOURCES[5],
    publishedAt: "2024-11-27T16:00:00Z",
    severity: "medium",
    truthScore: 0.91,
    politicianIds: ["pol-haddad", "pol-lula"],
    tags: ["fiscal", "economia", "orcamento"],
  },
  {
    id: "art-007",
    title: "Marina Silva anuncia desmatamento zero na Amazônia para 2030",
    summary: "A ministra Marina Silva anunciou meta ambiciosa de desmatamento zero na Amazônia até 2030, com plano de ação envolvendo fiscalização e incentivos econômicos.",
    url: "https://exemplo.poder360.com.br/ambiente/marina-silva-desmatamento-zero-2030.html",
    source: NEWS_SOURCES[6],
    publishedAt: "2024-07-05T08:00:00Z",
    severity: "info",
    truthScore: 0.94,
    politicianIds: ["pol-marina"],
    tags: ["amazonia", "meio-ambiente", "desmatamento"],
  },
  {
    id: "art-008",
    title: "Lira acumula suspeitas de irregularidades em contratos do Nordeste",
    summary: "Investigação do Ministério Público Federal aponta irregularidades em contratos firmados na época em que Arthur Lira era presidente da Câmara.",
    url: "https://exemplo.theintercept.com/brasil/lira-irregularidades-contratos.html",
    source: NEWS_SOURCES[7],
    publishedAt: "2024-09-18T13:00:00Z",
    severity: "critical",
    truthScore: 0.85,
    politicianIds: ["pol-lira"],
    tags: ["contratos", "corrupcao", "mpf"],
  },
  {
    id: "art-009",
    title: "Gleisi Hoffmann defende reforma política ampla no Brasil",
    summary: "A presidente do PT, Gleisi Hoffmann, defendeu reforma política que inclua financiamento público exclusivo de campanhas e mudanças no sistema eleitoral.",
    url: "https://exemplo.folha.uol.com.br/poder/2024/04/gleisi-reforma-politica.html",
    source: NEWS_SOURCES[0],
    publishedAt: "2024-04-22T10:30:00Z",
    severity: "low",
    truthScore: 0.89,
    politicianIds: ["pol-gleisi"],
    tags: ["reforma-politica", "eleicoes"],
  },
  {
    id: "art-010",
    title: "Temer condenado por corrupção passiva e lavagem de dinheiro",
    summary: "O ex-presidente Michel Temer foi condenado pelo TRF-3 a 13 anos de prisão por corrupção passiva e lavagem de dinheiro relacionados ao porto de Santos.",
    url: "https://exemplo.g1.globo.com/politica/temer-condenado-porto-santos.html",
    source: NEWS_SOURCES[1],
    publishedAt: "2024-02-14T17:00:00Z",
    severity: "critical",
    truthScore: 0.97,
    politicianIds: ["pol-temer"],
    tags: ["condenacao", "corrupcao", "lavagem"],
  },
  {
    id: "art-011",
    title: "Weintraub volta ao Brasil e enfrenta inquéritos na PF",
    summary: "O ex-ministro Abraham Weintraub retornou ao Brasil após período nos EUA e passou a responder por inquéritos na Polícia Federal relacionados à sua gestão.",
    url: "https://exemplo.estadao.com.br/politica/weintraub-volta-brasil-inqueritos.html",
    source: NEWS_SOURCES[2],
    publishedAt: "2024-10-05T11:30:00Z",
    severity: "critical",
    truthScore: 0.87,
    politicianIds: ["pol-weintraub"],
    tags: ["pf", "inquerito", "ministerio-educacao"],
  },
  {
    id: "art-012",
    title: "Tabata Amaral lidera ranking de presença em votações na Câmara",
    summary: "A deputada Tabata Amaral aparece no topo do ranking de presença em votações da Câmara dos Deputados, com 97% de participação em 2024.",
    url: "https://exemplo.poder360.com.br/congresso/tabata-amaral-presenca-camara.html",
    source: NEWS_SOURCES[6],
    publishedAt: "2024-12-01T09:00:00Z",
    severity: "info",
    truthScore: 0.96,
    politicianIds: ["pol-tabata"],
    tags: ["camara", "presenca", "votacoes"],
  },
  {
    id: "art-013",
    title: "Dilma Rousseff comanda BRICS em reunião com líderes mundiais",
    summary: "A ex-presidenta Dilma Rousseff, atual presidente do Novo Banco de Desenvolvimento (NDB/BRICS), se reuniu com líderes mundiais para discutir financiamento de projetos.",
    url: "https://exemplo.agenciabrasil.ebc.com.br/internacional/dilma-brics-ndb.html",
    source: NEWS_SOURCES[5],
    publishedAt: "2024-03-28T12:00:00Z",
    severity: "low",
    truthScore: 0.91,
    politicianIds: ["pol-dilma"],
    tags: ["brics", "internacional", "ndb"],
  },
  {
    id: "art-014",
    title: "Paulo Guedes presta depoimento sobre uso de offshores",
    summary: "O ex-ministro Paulo Guedes prestou depoimento à CPI para explicar a manutenção de investimentos em offshores no exterior durante seu mandato como ministro.",
    url: "https://exemplo.theintercept.com/brasil/guedes-offshores-cpi.html",
    source: NEWS_SOURCES[7],
    publishedAt: "2024-07-19T14:30:00Z",
    severity: "high",
    truthScore: 0.86,
    politicianIds: ["pol-guedes"],
    tags: ["offshore", "cpi", "conflito-interesse"],
  },
  {
    id: "art-015",
    title: "Eduardo Cunha volta a ser julgado no Supremo por peculato",
    summary: "O ex-presidente da Câmara Eduardo Cunha enfrenta novo julgamento no STF relacionado a acusações de peculato e corrupção na Petrobras.",
    url: "https://exemplo.folha.uol.com.br/poder/2024/08/cunha-julgamento-stf-peculato.html",
    source: NEWS_SOURCES[0],
    publishedAt: "2024-08-22T10:00:00Z",
    severity: "critical",
    truthScore: 0.94,
    politicianIds: ["pol-cunha"],
    tags: ["peculato", "stf", "petrobras"],
  },
  {
    id: "art-016",
    title: "Ciro Gomes critica postura do governo Lula frente à economia",
    summary: "O ex-candidato à presidência Ciro Gomes fez duras críticas à política econômica do governo Lula, especialmente em relação à taxa de juros e ao déficit fiscal.",
    url: "https://exemplo.estadao.com.br/politica/ciro-gomes-critica-governo-lula.html",
    source: NEWS_SOURCES[2],
    publishedAt: "2024-09-10T08:30:00Z",
    severity: "low",
    truthScore: 0.88,
    politicianIds: ["pol-ciro"],
    tags: ["economia", "oposicao", "juros"],
  },
  {
    id: "art-017",
    title: "Kim Kataguiri propõe projeto de lei contra nepotismo nos municípios",
    summary: "O deputado Kim Kataguiri apresentou PL que estabelece regras mais rígidas contra o nepotismo em prefeituras e câmaras municipais de todo o país.",
    url: "https://exemplo.poder360.com.br/congresso/kim-kataguiri-nepotismo-pl.html",
    source: NEWS_SOURCES[6],
    publishedAt: "2024-06-03T11:00:00Z",
    severity: "info",
    truthScore: 0.93,
    politicianIds: ["pol-kim"],
    tags: ["nepotismo", "pl", "municipios"],
  },
  {
    id: "art-018",
    title: "Rodrigo Maia defende aprovação de reformas estruturais urgentes",
    summary: "O ex-presidente da Câmara Rodrigo Maia alertou que o Brasil precisa aprovar reformas estruturais urgentes para retomar o crescimento econômico sustentável.",
    url: "https://exemplo.uol.com.br/politica/rodrigo-maia-reformas-estruturais.htm",
    source: NEWS_SOURCES[3],
    publishedAt: "2024-05-28T09:30:00Z",
    severity: "info",
    truthScore: 0.9,
    politicianIds: ["pol-rodrigo-maia"],
    tags: ["reformas", "economia", "camara"],
  },
  {
    id: "art-019",
    title: "Petrobras tem lucro recorde sob gestão indicada pelo governo Lula",
    summary: "A Petrobras registrou lucro líquido de R$ 124 bilhões em 2023, o maior da história da empresa, gerando debate sobre distribuição de dividendos.",
    url: "https://exemplo.g1.globo.com/economia/petrobras-lucro-recorde-2023.html",
    source: NEWS_SOURCES[1],
    publishedAt: "2024-02-08T16:00:00Z",
    severity: "medium",
    truthScore: 0.96,
    politicianIds: ["pol-lula", "pol-haddad"],
    tags: ["petrobras", "lucro", "dividendos"],
  },
  {
    id: "art-020",
    title: "STF decide manter bloqueio de passaporte de Bolsonaro",
    summary: "O Supremo Tribunal Federal manteve o bloqueio do passaporte do ex-presidente Jair Bolsonaro no âmbito das investigações sobre tentativa de golpe.",
    url: "https://exemplo.folha.uol.com.br/poder/2024/01/stf-passaporte-bolsonaro-bloqueado.html",
    source: NEWS_SOURCES[0],
    publishedAt: "2024-01-15T14:00:00Z",
    severity: "critical",
    truthScore: 0.97,
    politicianIds: ["pol-bolsonaro"],
    tags: ["stf", "passaporte", "golpe"],
  },
  {
    id: "art-021",
    title: "Amoêdo doa R$ 10 milhões para projetos sociais em SP",
    summary: "O ex-candidato à presidência João Amoêdo anunciou doação de R$ 10 milhões para projetos de educação e empreendedorismo em comunidades carentes de São Paulo.",
    url: "https://exemplo.agenciabrasil.ebc.com.br/cidadania/amoedo-doacao-projetos-sociais.html",
    source: NEWS_SOURCES[5],
    publishedAt: "2024-04-10T10:00:00Z",
    severity: "info",
    truthScore: 0.91,
    politicianIds: ["pol-amoedo"],
    tags: ["educacao", "social", "filantropia"],
  },
  {
    id: "art-022",
    title: "Lula veta projeto que ampliava imunidade parlamentar",
    summary: "O presidente Lula vetou projeto de lei aprovado pelo Congresso que ampliava a imunidade parlamentar, citando risco de impunidade e retrocesso democrático.",
    url: "https://exemplo.estadao.com.br/politica/lula-veta-imunidade-parlamentar.html",
    source: NEWS_SOURCES[2],
    publishedAt: "2024-10-25T15:00:00Z",
    severity: "medium",
    truthScore: 0.95,
    politicianIds: ["pol-lula", "pol-gleisi"],
    tags: ["imunidade", "veto", "congresso"],
  },
  {
    id: "art-023",
    title: "Fux critica tentativas de interferência política no Judiciário",
    summary: "O ministro Luiz Fux do STF criticou publicamente tentativas de pressão e interferência política nas decisões do Poder Judiciário, afirmando que a independência judicial é inegociável.",
    url: "https://exemplo.poder360.com.br/judiciario/fux-critica-interferencia-politica-judiciario.html",
    source: NEWS_SOURCES[6],
    publishedAt: "2024-08-30T11:00:00Z",
    severity: "info",
    truthScore: 0.93,
    politicianIds: ["pol-fux"],
    tags: ["stf", "judiciario", "independencia"],
  },
  {
    id: "art-024",
    title: "CPI investiga desvios no Ministério da Educação durante governo Bolsonaro",
    summary: "Comissão Parlamentar de Inquérito instaurada para investigar supostos desvios de verbas públicas no Ministério da Educação durante a gestão Bolsonaro.",
    url: "https://exemplo.theintercept.com/brasil/cpi-ministerio-educacao-bolsonaro.html",
    source: NEWS_SOURCES[7],
    publishedAt: "2024-03-05T09:00:00Z",
    severity: "critical",
    truthScore: 0.87,
    politicianIds: ["pol-bolsonaro", "pol-weintraub"],
    tags: ["cpi", "educacao", "desvio"],
  },
  {
    id: "art-025",
    title: "Alckmin propõe fundo de investimento em infraestrutura para Norte e Nordeste",
    summary: "O vice-presidente Alckmin apresentou proposta para criação de fundo de R$ 50 bilhões para financiar projetos de infraestrutura nas regiões Norte e Nordeste do Brasil.",
    url: "https://exemplo.agenciabrasil.ebc.com.br/politica/alckmin-fundo-infraestrutura.html",
    source: NEWS_SOURCES[5],
    publishedAt: "2024-11-08T10:00:00Z",
    severity: "low",
    truthScore: 0.92,
    politicianIds: ["pol-alckmin"],
    tags: ["infraestrutura", "desenvolvimento", "nordeste"],
  },
  {
    id: "art-026",
    title: "Dilma e o legado do impeachment: 8 anos depois",
    summary: "Análise sobre o impacto do impeachment de Dilma Rousseff na democracia brasileira, oito anos após o processo que afastou a então presidenta do cargo.",
    url: "https://exemplo.folha.uol.com.br/poder/2024/08/dilma-legado-impeachment-8-anos.html",
    source: NEWS_SOURCES[0],
    publishedAt: "2024-08-31T12:00:00Z",
    severity: "medium",
    truthScore: 0.89,
    politicianIds: ["pol-dilma", "pol-temer", "pol-cunha"],
    tags: ["impeachment", "democracia", "historia"],
  },
  {
    id: "art-027",
    title: "Marina Silva recebe prêmio internacional de sustentabilidade",
    summary: "A ministra Marina Silva recebeu o Prêmio Goldman de Meio Ambiente, considerado o Nobel ambiental, por seu trabalho na proteção da Amazônia.",
    url: "https://exemplo.g1.globo.com/natureza/marina-silva-premio-goldman-ambiental.html",
    source: NEWS_SOURCES[1],
    publishedAt: "2024-04-22T14:00:00Z",
    severity: "info",
    truthScore: 0.98,
    politicianIds: ["pol-marina"],
    tags: ["amazonia", "premio", "sustentabilidade"],
  },
  {
    id: "art-028",
    title: "Guedes acusado de negligência no combate à corrupção no ministério",
    summary: "Ex-assessores do Ministério da Economia acusam Paulo Guedes de ter sido negligente ao não adotar medidas de controle interno suficientes para coibir irregularidades.",
    url: "https://exemplo.theintercept.com/brasil/guedes-negligencia-corrupcao-ministerio.html",
    source: NEWS_SOURCES[7],
    publishedAt: "2024-06-14T13:30:00Z",
    severity: "high",
    truthScore: 0.82,
    politicianIds: ["pol-guedes"],
    tags: ["corrupcao", "ministerio", "negligencia"],
  },
  {
    id: "art-029",
    title: "Moro anuncia candidatura à Presidência para 2026",
    summary: "O senador Sergio Moro confirmou sua pré-candidatura à presidência da República nas eleições de 2026, defendendo plataforma liberal e anticorrupção.",
    url: "https://exemplo.poder360.com.br/eleicoes/moro-precandidatura-presidencia-2026.html",
    source: NEWS_SOURCES[6],
    publishedAt: "2024-12-05T11:00:00Z",
    severity: "info",
    truthScore: 0.96,
    politicianIds: ["pol-moro"],
    tags: ["eleicoes", "candidatura", "2026"],
  },
  {
    id: "art-030",
    title: "Tabata Amaral apresenta PL para educação de qualidade universal",
    summary: "A deputada Tabata Amaral apresentou projeto de lei que estabelece metas de qualidade para o ensino básico público, com mecanismos de monitoramento e responsabilização.",
    url: "https://exemplo.agenciabrasil.ebc.com.br/educacao/tabata-amaral-pl-educacao-qualidade.html",
    source: NEWS_SOURCES[5],
    publishedAt: "2024-05-14T09:00:00Z",
    severity: "info",
    truthScore: 0.94,
    politicianIds: ["pol-tabata"],
    tags: ["educacao", "pl", "ensino-basico"],
  },
];

// ─── Legal Milestones ─────────────────────────────────────────────────────────

export const LEGAL_MILESTONES: LegalMilestone[] = [
  {
    id: "ms-lula-condenado-lj",
    politicianId: "pol-lula",
    title: "Condenado por Sérgio Moro na Lava Jato",
    description: "Lula foi condenado pelo então juiz Sérgio Moro a 9,5 anos de prisão por corrupção passiva e lavagem de dinheiro no caso triplex.",
    type: "conviction",
    date: "2017-07-12T00:00:00Z",
    court: "13ª Vara Federal de Curitiba",
    processNumber: "5046512-94.2016.4.04.7000",
    severity: "critical",
  },
  {
    id: "ms-lula-preso",
    politicianId: "pol-lula",
    title: "Preso após esgotar recursos de segunda instância",
    description: "Lula se entregou à Polícia Federal em Curitiba após o STF decidir, por 6 a 5, que a prisão em segunda instância era constitucional.",
    type: "conviction",
    date: "2018-04-07T00:00:00Z",
    court: "Polícia Federal — Curitiba",
    severity: "critical",
  },
  {
    id: "ms-lula-solto",
    politicianId: "pol-lula",
    title: "Solto após 580 dias preso por decisão do STF",
    description: "O STF revisou sua posição sobre prisão em segunda instância e Lula foi libertado após 580 dias de reclusão em Curitiba.",
    type: "acquittal",
    date: "2019-11-08T00:00:00Z",
    court: "Supremo Tribunal Federal",
    severity: "high",
  },
  {
    id: "ms-lula-suspeicao-moro",
    politicianId: "pol-lula",
    title: "STF declara Moro parcial e anula condenações",
    description: "O STF declarou por 3 a 2 que o juiz Sérgio Moro foi parcial no julgamento de Lula, anulando todas as condenações da Lava Jato.",
    type: "acquittal",
    date: "2021-03-08T00:00:00Z",
    court: "Supremo Tribunal Federal",
    severity: "critical",
  },
  {
    id: "ms-bolsonaro-indiciado-golpe",
    politicianId: "pol-bolsonaro",
    title: "Indiciado pela PF por tentativa de golpe de Estado",
    description: "A Polícia Federal indiciou Bolsonaro por tentativa de golpe de Estado, abolição violenta do Estado Democrático de Direito e dano ao erário.",
    type: "indictment",
    date: "2024-11-22T00:00:00Z",
    court: "Polícia Federal",
    severity: "critical",
  },
  {
    id: "ms-bolsonaro-passaporte-bloqueado",
    politicianId: "pol-bolsonaro",
    title: "Passaporte apreendido pelo STF",
    description: "O STF determinou a apreensão do passaporte de Bolsonaro no âmbito das investigações sobre tentativa de golpe de Estado.",
    type: "investigation",
    date: "2024-01-10T00:00:00Z",
    court: "Supremo Tribunal Federal",
    severity: "critical",
  },
  {
    id: "ms-temer-condenado",
    politicianId: "pol-temer",
    title: "Condenado a 13 anos de prisão pelo TRF-3",
    description: "Michel Temer foi condenado pelo Tribunal Regional Federal da 3ª Região a 13 anos de prisão por corrupção passiva e lavagem de dinheiro.",
    type: "conviction",
    date: "2024-02-14T00:00:00Z",
    court: "TRF-3",
    severity: "critical",
  },
  {
    id: "ms-cunha-condenado",
    politicianId: "pol-cunha",
    title: "Condenado na Lava Jato a 15 anos de prisão",
    description: "Eduardo Cunha foi condenado a 15 anos e 4 meses de prisão por corrupção passiva, lavagem de dinheiro e evasão de divisas.",
    type: "conviction",
    date: "2017-03-30T00:00:00Z",
    court: "13ª Vara Federal de Curitiba",
    severity: "critical",
  },
  {
    id: "ms-flavio-rachadinha",
    politicianId: "pol-flavio",
    title: "Caso 'rachadinha' investigado pelo MPRJ",
    description: "O Ministério Público do Rio de Janeiro abriu investigação formal sobre o desvio de parte dos salários de assessores do gabinete de Flávio Bolsonaro.",
    type: "investigation",
    date: "2018-12-06T00:00:00Z",
    court: "MPRJ",
    severity: "critical",
  },
  {
    id: "ms-lira-investigado",
    politicianId: "pol-lira",
    title: "MPF investiga irregularidades em contratos",
    description: "O Ministério Público Federal abriu investigação para apurar supostas irregularidades em contratos firmados durante a presidência de Lira na Câmara.",
    type: "investigation",
    date: "2024-09-18T00:00:00Z",
    court: "MPF",
    severity: "critical",
  },
  {
    id: "ms-dilma-impeachment",
    politicianId: "pol-dilma",
    title: "Impeachment aprovado pelo Senado",
    description: "O Senado Federal aprovou o impeachment de Dilma Rousseff por 61 votos a 20, afastando-a definitivamente da presidência por crime de responsabilidade fiscal.",
    type: "impeachment",
    date: "2016-08-31T00:00:00Z",
    court: "Senado Federal",
    severity: "critical",
  },
  {
    id: "ms-moro-suspeicao",
    politicianId: "pol-moro",
    title: "STF declara Moro parcial no julgamento de Lula",
    description: "O Supremo Tribunal Federal declarou a parcialidade de Sérgio Moro no processo de Lula, invalidando sua atuação como juiz nos casos da Lava Jato.",
    type: "conviction",
    date: "2021-03-23T00:00:00Z",
    court: "Supremo Tribunal Federal",
    severity: "critical",
  },
];

// ─── Relationships ─────────────────────────────────────────────────────────────

export const RELATIONSHIPS: Relationship[] = [
  {
    id: "rel-001",
    politicianId: "pol-lula",
    entityId: "ent-petrobras",
    type: "investigation",
    description: "Investigado por corrupção envolvendo contratos na Petrobras durante seu governo",
    sources: ["lava-jato"],
  },
  {
    id: "rel-002",
    politicianId: "pol-lula",
    entityId: "ent-odebrecht",
    type: "investigation",
    description: "Investigado por receber propinas da Odebrecht por meio de reformas no sítio de Atibaia",
    sources: ["lava-jato"],
  },
  {
    id: "rel-003",
    politicianId: "pol-temer",
    entityId: "ent-odebrecht",
    type: "investigation",
    description: "Acusado de receber propina de R$ 1 milhão da Odebrecht por autorizar obras do porto de Santos",
    sources: ["mpf", "pf"],
  },
  {
    id: "rel-004",
    politicianId: "pol-cunha",
    entityId: "ent-petrobras",
    type: "donation",
    description: "Acusado de receber propinas em contas no exterior relacionadas a contratos na Petrobras",
    value: 50000000,
    sources: ["lava-jato", "mpf"],
  },
  {
    id: "rel-005",
    politicianId: "pol-haddad",
    entityId: "ent-bndes",
    type: "contract",
    description: "Ministro da Fazenda supervisiona a política de crédito e financiamento do BNDES",
    sources: ["tesouro-nacional"],
  },
  {
    id: "rel-006",
    politicianId: "pol-dilma",
    entityId: "ent-petrobras",
    type: "board_member",
    description: "Foi presidente do Conselho de Administração da Petrobras de 2003 a 2010",
    startDate: "2003-01-01T00:00:00Z",
    endDate: "2010-12-31T00:00:00Z",
    sources: ["petrobras-ata"],
  },
  {
    id: "rel-007",
    politicianId: "pol-guedes",
    entityId: "ent-bndes",
    type: "contract",
    description: "Supervisionou o BNDES como ministro da Economia, com foco em privatizações",
    startDate: "2019-01-01T00:00:00Z",
    endDate: "2022-12-31T00:00:00Z",
    sources: ["governo-federal"],
  },
  {
    id: "rel-008",
    politicianId: "pol-bolsonaro",
    entityId: "ent-mpf",
    type: "investigation",
    description: "Investigado pelo MPF por tentativa de golpe, falsificação de cartão vacinal e outros crimes",
    sources: ["pf", "stf"],
  },
  {
    id: "rel-009",
    politicianId: "pol-lira",
    entityId: "ent-mpf",
    type: "investigation",
    description: "MPF investiga irregularidades em contratos durante sua presidência da Câmara",
    sources: ["mpf", "tcu"],
  },
  {
    id: "rel-010",
    politicianId: "pol-marina",
    entityId: "ent-cni",
    type: "investigation",
    description: "Tensão entre agenda ambiental da ministra e interesses do setor industrial",
    sources: ["folha", "estadao"],
  },
  {
    id: "rel-011",
    politicianId: "pol-haddad",
    entityId: "ent-tcu",
    type: "investigation",
    description: "TCU analisa conformidade das medidas fiscais com a LRF e a Emenda Constitucional do teto de gastos",
    sources: ["tcu"],
  },
  {
    id: "rel-012",
    politicianId: "pol-gleisi",
    entityId: "ent-cut",
    type: "business_partner",
    description: "Gleisi Hoffmann tem histórico de colaboração com a CUT em pautas trabalhistas",
    sources: ["publico"],
  },
  {
    id: "rel-013",
    politicianId: "pol-moro",
    entityId: "ent-mpf",
    type: "business_partner",
    description: "Trabalhou em estreita colaboração com o MPF durante a Operação Lava Jato",
    startDate: "2014-03-01T00:00:00Z",
    endDate: "2018-11-01T00:00:00Z",
    sources: ["lava-jato"],
  },
  {
    id: "rel-014",
    politicianId: "pol-flavio",
    entityId: "ent-mpf",
    type: "investigation",
    description: "MPRJ investiga desvio de salários de assessores (rachadinha) com possível conexão com o MPF federal",
    sources: ["mprj", "pf"],
  },
  {
    id: "rel-015",
    politicianId: "pol-alckmin",
    entityId: "ent-bndes",
    type: "contract",
    description: "Como vice-presidente, articula financiamento pelo BNDES para projetos de infraestrutura",
    startDate: "2023-01-01T00:00:00Z",
    sources: ["governo-federal"],
  },
];

// ─── Graph Data ───────────────────────────────────────────────────────────────

export function getGraphData(): GraphData {
  const nodes = [
    ...POLITICIANS.map((p) => ({
      id: p.id,
      type: "politician" as const,
      label: p.name,
      slug: p.slug,
      party: p.party,
      partyColor: p.partyColor,
      score: p.score,
    })),
    ...ENTITIES.map((e) => ({
      id: e.id,
      type: "entity" as const,
      label: e.name,
      entityType: e.type,
    })),
  ];

  const edges = RELATIONSHIPS.map((r) => ({
    id: r.id,
    source: r.politicianId,
    target: r.entityId,
    type: r.type,
    value: r.value,
    label: r.type.replace("_", " "),
  }));

  return { nodes, edges };
}

// ─── Stats ────────────────────────────────────────────────────────────────────

export function getStats(): Stats {
  const totalScore = POLITICIANS.reduce((acc, p) => acc + p.score, 0);
  const criticalCount = POLITICIANS.filter(
    (p) => p.maxSeverity === "critical"
  ).length;

  return {
    totalPoliticians: POLITICIANS.length,
    totalArticles: ARTICLES.length,
    totalEntities: ENTITIES.length,
    totalRelationships: RELATIONSHIPS.length,
    avgScore: Math.round(totalScore / POLITICIANS.length),
    criticalCount,
  };
}

// ─── Helper Functions ─────────────────────────────────────────────────────────

export function getPoliticianBySlug(slug: string): Politician | undefined {
  return POLITICIANS.find((p) => p.slug === slug);
}

export function getArticlesForPolitician(politicianId: string): Article[] {
  return ARTICLES.filter((a) => a.politicianIds.includes(politicianId));
}

export function getMilestonesForPolitician(politicianId: string): LegalMilestone[] {
  return LEGAL_MILESTONES.filter((m) => m.politicianId === politicianId);
}

export function getRelationshipsForPolitician(politicianId: string): Relationship[] {
  return RELATIONSHIPS.filter((r) => r.politicianId === politicianId);
}

export function searchPoliticians(query: string): Politician[] {
  const q = query.toLowerCase();
  return POLITICIANS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.party.toLowerCase().includes(q) ||
      p.uf.toLowerCase().includes(q) ||
      p.role.toLowerCase().includes(q)
  );
}

export function getPartiesList(): string[] {
  return [...new Set(POLITICIANS.map((p) => p.party))].sort();
}

export function getUFList(): string[] {
  return [...new Set(POLITICIANS.map((p) => p.uf))].sort();
}

export function getRanking(
  party?: string,
  uf?: string,
  page = 1,
  pageSize = 20,
  sortBy = "score",
  sortOrder: "asc" | "desc" = "asc"
): { data: Politician[]; total: number } {
  let filtered = [...POLITICIANS];

  if (party) filtered = filtered.filter((p) => p.party === party);
  if (uf) filtered = filtered.filter((p) => p.uf === uf);

  const severityWeight: Record<string, number> = {
    critical: 4,
    high: 3,
    medium: 2,
    low: 1,
    info: 0,
  };

  filtered.sort((a, b) => {
    let comparison = 0;
    switch (sortBy) {
      case "name":
        comparison = a.name.localeCompare(b.name);
        break;
      case "score":
        comparison = a.score - b.score;
        break;
      case "articleCount":
        comparison = a.articleCount - b.articleCount;
        break;
      case "maxSeverity":
        comparison =
          severityWeight[a.maxSeverity] - severityWeight[b.maxSeverity];
        break;
      case "party":
        comparison = a.party.localeCompare(b.party);
        break;
      case "uf":
        comparison = a.uf.localeCompare(b.uf);
        break;
    }
    return sortOrder === "desc" ? -comparison : comparison;
  });

  const total = filtered.length;
  const start = (page - 1) * pageSize;
  const data = filtered.slice(start, start + pageSize);

  return { data, total };
}
